const mongoose=require('mongoose')
const Schema=mongoose.Schema({
    RegistrationNO:{
        type:String,
        required:true,
        unique:true,
    },
    Name:{
        type:String,
        required:true,
        uppercase:true,
    },
    FatherName:{
        type:String,
        required:true,
        uppercase:true,
       },
    MotherName:{
        type:String,
        required:true,
        uppercase:true,
       },
    Gender:{
        type:String,
        required:true,
        uppercase:true,
       },
    Categories:{
        type:String,
        required:true,
        uppercase:true,
       },
    Caste:{
        type:String,
        required:true,
        uppercase:true,
       },
    Email:{
        type:String,
        required:true,
        unique:true,
       },
    Mobile:{
        type:Number,
        required:true,
        unique:true,
       },
    AadharNO:{
        type:Number,
        required:true,
        unique:true,
       },
    DOB:{
        type:String,
        required:true,
       },
    Country:{
        type:String,
        required:true,
        uppercase:true,
       },
    State:{
        type:String,
        required:true,
        uppercase:true,
       },
    City:{
        type:String,
        required:true,
        uppercase:true,
       },
    Address:{
        type:String,
        required:true,
        uppercase:true,
    },
    HighSchoolRollNO:{
        type:Number,
        required:true,
        uppercase:true,
    },
    HighSchoolYear:{
        type:Number,
        required:true,
    },
    InterMediateRollNO:{
        type:Number,
        required:true,
        uppercase:true,
    },
    InterMediateYear:{
        type:Number,
        required:true,
    },
    GurationCourse:{
        type:String,
        required:true,
        uppercase:true,
    },
    GurationUniversityName:{
        type:String,
        required:true,
        uppercase:true,
    },
    GurationRollNO:{
        type:Number,
        required:true,
        uppercase:true,
    },
    GurationYear:{
        type:Number,
        required:true,
    },
    ClassORCourse:{
        type:Array,
        required:true,
    },
    RollNO:{
        type:Array,
        required:true,
    },
    MarksObtained:{
        type:Array,
        required:true,
    },
    MaxMarks:{
        type:Array,
        required:true,
    },
    Parcentage:{
        type:Array,
        required:true,
    },
    BoardORUniversity:{
        type:Array,
        required:true,
    },
    RegisterDate:{
        type:String,
        required:true
    },
    RegisterTime:{
        type:String,
        required:true
    },
    Varified:{
        type:Number,
        required:true,
    }
})
const entranceExamRegistrationPD=mongoose.model('entranceExamRegistrationPD',Schema)
module.exports=entranceExamRegistrationPD;