const { default: mongoose } = require("mongoose");

const Schema=mongoose.Schema({
      RequestNO:{
        type:Number,
        required:true,
        unique:true,
      },
      Name:{
        type:String,
        required:true,
        uppercase:true,
      },
      Email:{
        type:String,
        required:true,
      },
      CollegeID:{
        type:String,
        required:true,
      },  
      BookName:{
        type:String,
        required:true,
      },
      BookAuthorName:{
        type:String,
        required:true,
      },
      RequestDate:{
        type:String,
        default:0,
      },
      RequestTime:{
          type:String,
          default:0,
      },
      SubmitDate:{
        type:String,
        default:0,
      },
      RequestStatus:{
        type:String,
        default:'Your Request is Pending',
      },
      Status:{
        type:String,
        default:'Pending',
      },
      BookIssueBookNO:{
        type:Number,
        default:0,
      },
      BookNOIssueDate:{
        type:String,
        default:0,
      },
      BookRejectReason:{
        type:String, 
        default:0,
      },
      BookRejectDate:{
        type:String,
        default:0,
      },
      BookIssueVarified:{
        type:Number,
        default:0,
      },
      BookIssueOTP:{
        type:Number,
        default:0,
      },
      BookIssueOTPSend:{
        type:Number,
        default:0,
      },
      BookIssuedDate:{
        type:String,
        default:0,
      },
      BookIssuedTime:{
        type:String,
        default:0,
      },
})
const StudentBookRequestModel=mongoose.model('StudentBookRequest',Schema)
module.exports=StudentBookRequestModel