const mongoose=require('mongoose')
const Schema=mongoose.Schema({
    AdmissionNO:{
        type:String,
        required:true,
        unique:true,
    },
    EnrollmentNO:{ 
        type:Number,
        default:0,
    },
    AcademicSession:{
        type:String,
        required:true,
    },
    AdmissionFor:{ 
        type:String,
        required:true,
    }, 
    Name:{
        type:String,
        required:true,
        uppercase:true,
    },
    FatherName:{
        type:String,
        required:true,
        uppercase:true,
       },
    MotherName:{
        type:String,
        required:true,
        uppercase:true,
       },
    Gender:{
        type:String,
        required:true,
        uppercase:true,
       },
    Religion:{
        type:String,
        required:true,
        uppercase:true,
       },
    Caste:{
        type:String,
        required:true,
        uppercase:true,
       },
    Email:{
        type:String,
        required:true,
        unique:true,
       },
    Mobile:{
        type:Number,
        required:true,
        unique:true,
       },
    AadharNO:{
        type:Number,
        required:true,
        unique:true,
       },
    DOB:{
        type:String,
        required:true,
       },
    Password:{
        type:String,
        required:true,
    },
    RegisterDate:{
        type:String,
        default:0,
    },
    RegisterTime:{
        type:String,
        default:0,
    },
    EmailOTP:{
        type:Number,
        default:0,
       },
    MobileOTP:{
        type:Number,
        default:0,
       },
    EmailVarified:{
        type:Number,
        default:0,
       },
    MobileVarified:{
        type:Number,
        default:0,
       },
    Varified:{
        type:Number,
        default:0,
    }
})
const admissionRegistration=mongoose.model('admissionRegistration',Schema)
module.exports=admissionRegistration;